feat: Set `workers` through env variable, improved defaults
arcee-ai/fastmlx pull request #15
Opened 2024-07-12 07:58 UTC by SiddhantSadangi

The number of workers can now be specified using the `FASTMLX_ENV_VARIABLE`.
If this is not set, and `workers` is not provided, it defaults to 2 or the number of CPU cores minus 4, whichever is higher. 

⚠️**Note**: Haven't tested this locally as I don't have a Mac

2024-07-12 08:22 UTC, Blaizzy commented
Hey @SiddhantSadangi 

Thanks for the great PR! ❤️

2024-07-12 08:25 UTC, Blaizzy commented on fastmlx/fastmlx.py
> +        default=os.getenv("FASTMLX_NUM_WORKERS", max(2, os.cpu_count() - 4)),
This awesome!

Could you clarify why `cpu_count - 4` ?

2024-07-12 08:29 UTC, SiddhantSadangi commented on fastmlx/fastmlx.py
> +        default=os.getenv("FASTMLX_NUM_WORKERS", max(2, os.cpu_count() - 4)),
`- 4` provides a safe buffer to prevent CPU RAM overflow, and also prevents the user multitask decently with 4 CPUs available for other tasks

2024-07-12 10:02 UTC, Blaizzy commented on fastmlx/fastmlx.py
> +        default=os.getenv("FASTMLX_NUM_WORKERS", max(2, os.cpu_count() - 4)),
I see, that makes sense! 

Apple Silicon devices have 4-16 Performance cores and 2-8 Efficiency cores. The current allocation might use most or all Performance cores, leaving only Efficiency cores for other tasks. On my 10P/4E core device, this would allocate all 10 Performance cores and 2GB URAM to fastmlx at startup.

My stress tests with 8 parallel requests to 2B and 9B param models used only 2-4 workers out of 10. I propose setting the default to 15% or 25% of total CPU count. This would offer:

Improved multitasking
Better energy efficiency
Reduced heat generation
Lower memory pressure

For M-series chip core counts, see: https://en.wikipedia.org/wiki/Apple_silicon#M_series

Something like this: 
`max(2, int(os.cpu_count() * 0.25))`

2024-07-12 10:19 UTC, SiddhantSadangi commented on fastmlx/fastmlx.py
> +        default=os.getenv("FASTMLX_NUM_WORKERS", max(2, os.cpu_count() - 4)),
Sounds good.

We could also set the %age of CPUs using the `FASTMLX_NUM_WORKERS` variable or the `workers` arg. If it is an integer, use that many workers. If a float, use that percent of CPUs.

Lemme know what you think

2024-07-12 10:57 UTC, Blaizzy commented on fastmlx/fastmlx.py
> +        default=os.getenv("FASTMLX_NUM_WORKERS", max(2, os.cpu_count() - 4)),
That's a great idea, let's do it!👌🏽

2024-07-13 00:10 UTC, stewartugelow commented on fastmlx/fastmlx.py
> +        default=os.getenv("FASTMLX_NUM_WORKERS", max(2, os.cpu_count() - 4)),
I was bored on a conference call and found the function on determining performance vs efficiency cores. After a little ChatGPT magic, it gave back the following:

```
import subprocess
import json
import psutil

def get_sysctl_value(key):
    try:
        result = subprocess.run(['sysctl', key], capture_output=True, text=True, check=True)
        return result.stdout.split(': ')[1].strip()
    except subprocess.CalledProcessError as e:
        print(f"An error occurred while running sysctl command: {e}")
        return None

# Performance cores
perf_physicalcpu = get_sysctl_value('hw.perflevel0.physicalcpu')
perf_physicalcpu_max = get_sysctl_value('hw.perflevel0.physicalcpu_max')
perf_logicalcpu = get_sysctl_value('hw.perflevel0.logicalcpu')
perf_logicalcpu_max = get_sysctl_value('hw.perflevel0.logicalcpu_max')

# Efficiency cores
eff_physicalcpu = get_sysctl_value('hw.perflevel1.physicalcpu')
eff_physicalcpu_max = get_sysctl_value('hw.perflevel1.physicalcpu_max')
eff_logicalcpu = get_sysctl_value('hw.perflevel1.logicalcpu')
eff_logicalcpu_max = get_sysctl_value('hw.perflevel1.logicalcpu_max')

# Chip type
chip_type = get_sysctl_value('machdep.cpu.brand_string')

# Memory information
memory_info = psutil.virtual_memory()

# Structure the information into a dictionary
system_info = {
    "chip_type": chip_type,
    "performance_cores": {
        "physical_cpu": perf_physicalcpu,
        "physical_cpu_max": perf_physicalcpu_max,
        "logical_cpu": perf_logicalcpu,
        "logical_cpu_max": perf_logicalcpu_max
    },
    "efficiency_cores": {
        "physical_cpu": eff_physicalcpu,
        "physical_cpu_max": eff_physicalcpu_max,
        "logical_cpu": eff_logicalcpu,
        "logical_cpu_max": eff_logicalcpu_max
    },
    "memory": {
        "total": memory_info.total,
        "available": memory_info.available,
        "used": memory_info.used,
        "free": memory_info.free
    }
}

# Convert the dictionary to a JSON string
system_info_json = json.dumps(system_info, indent=4)
```

# Print the JSON string
print(system_info_json)

2024-07-15 10:46 UTC, Blaizzy requested changes
Thank you very much Siddhant!

LGTM, just a few nits. Once they are resolved and tests cleared we can merge :)

2024-07-15 10:46 UTC, Blaizzy commented on fastmlx/fastmlx.py
> +def int_or_float(value):
Can we rename this to `parse_int_or_float` or `parse_numeric` ?

and refactor it to not use loops.
```suggestion
def int_or_float(value):
    """
    Convert string to int or float, or raise ArgumentTypeError.
    """
    try:
        return int(value)
    except ValueError:
        try:
            return float(value)
        except ValueError:
            raise argparse.ArgumentTypeError(f"{value} is not a valid number")
```

2024-07-15 10:46 UTC, Blaizzy commented on fastmlx/fastmlx.py
> +            _default_workers = max(1, int(os.cpu_count() * float(_num_workers_env)))
How about we refactor this into a function, for example:

```python
def calculate_default_workers() -> int:
    """Calculate the default number of workers based on environment variable."""
    default_workers = 2
    num_workers_env = os.getenv("FASTMLX_NUM_WORKERS")
    if num_workers_env:
        try:
            default_workers = int(num_workers_env)
        except ValueError:
            default_workers = max(1, int(os.cpu_count() * float(num_workers_env)))
    return default_workers
```

2024-07-15 10:53 UTC, Blaizzy commented on fastmlx/fastmlx.py
> +        default=os.getenv("FASTMLX_NUM_WORKERS", max(2, os.cpu_count() - 4)),
Thanks a lot @stewartugelow this is pretty cool! 

I get the entire system state including memory 👍🏾 

I'll keep this in mind because I think it will be handy down the line with distributed inference and other use cases.

2024-07-15 11:01 UTC, SiddhantSadangi commented on fastmlx/fastmlx.py
> +def int_or_float(value):
It's being used as a type indicator while adding args (https://github.com/SiddhantSadangi/fastmlx/blob/8c3a7b5911f872c87def720888fca549019cd032/fastmlx/fastmlx.py#L297), so I think this name makes more sense in that context (`type=int_or_float` instead of `type=parse_*`).

Regarding refactoring, done ✅

2024-07-15 11:42 UTC, Blaizzy commented on fastmlx/fastmlx.py
> +def int_or_float(value):
Makes sense!

2024-07-15 11:43 UTC, Blaizzy commented
Thanks!

I will merge as soon as the tests clear :)

2024-07-15 11:45 UTC, Blaizzy approved these changes
LGTM!

2024-07-15 11:47 UTC, merged