Implement Token Usage Tracking
arcee-ai/fastmlx pull request #27
Opened 2024-08-23 04:56 UTC by ZachZimm

This PR resolves issue #8 by adding token usage information to the response messages. The response conforms to the schema I found [here for non-streaming](https://help.openai.com/en/articles/6614209-how-do-i-check-my-token-usage) and [here for streaming, at the very bottom](https://cookbook.openai.com/examples/how_to_stream_completions). 
In this implementation, all streamed chunks include up-to-date information about token usage.

This streaming implementation differs slightly from openai's in that their api accepts a `stream_options: dict` parameter which can include `"include_usage"=True`, otherwise it will not stream back usage information. Additionally, they put forth a few rules about which chunks of the stream will contain usage data. 

I did not add a `count_tokens` function as suggested in the issue, as it seems better to do this during generation since we are already using the tokenizer and in the case of non-streaming we already had an array of prompt tokens.

2024-08-24 05:51 UTC, Blaizzy commented
Thank you very much for the great PR, @ZachZimm!

2024-08-24 05:58 UTC, Blaizzy commented
> 1. This streaming implementation differs slightly from openai's in that their api accepts a stream_options: dict parameter which can include "include_usage"=True, otherwise it will not stream back usage information. 
> 2. Additionally, they put forth a few rules about which chunks of the stream will contain usage data.

Can we implement this as well?

We need 1, to make it easier to define when we need it. 

And 2 is a simple implementation, all you need to do is to pass it before done (i.e., https://github.com/Blaizzy/fastmlx/blob/main/fastmlx/utils.py#L407).

2024-08-24 06:02 UTC, Blaizzy requested changes

2024-08-24 06:02 UTC, Blaizzy commented on fastmlx/utils.py
> +    # config["context_size"] = 1024
Nit: remove comments
```suggestion
```

2024-08-24 06:02 UTC, Blaizzy commented on fastmlx/utils.py
> +    print(f"Prompt tokens: {prompt_token_len}")
Why are we printing here?

2024-08-24 06:02 UTC, Blaizzy commented on fastmlx/utils.py
> +    # once here, and once in mlx.utils.stream_generate (lm_stream_generate)
Nit: remove comment

```suggestion
```

2024-08-24 06:02 UTC, Blaizzy commented on fastmlx/utils.py
>      prompt_tokens = mx.array(tokenizer.encode(prompt))
This will yield an error:

 AttributeError: 'Phi3VProcessor' object has no attribute 'encode'. Did you mean: 'decode'?

I would recommend checking out the MLX-VLM handles tokenizer:
https://github.com/Blaizzy/mlx-vlm/blob/main/mlx_vlm/utils.py#L864

2024-08-24 06:02 UTC, Blaizzy commented
Please run pre-commit to fix styling check errors.

2024-08-24 06:07 UTC, Blaizzy commented on fastmlx/utils.py
> +    print(f"Prompt tokens: {prompt_token_len}")
I actually like it. How about we add it as part of logging in a separate PR?

2024-08-25 04:00 UTC, ZachZimm commented on fastmlx/utils.py
>      prompt_tokens = mx.array(tokenizer.encode(prompt))
I'm not sure this is an issue for this PR as I did not add this call to `tokenizer.encode()`. Certainly worth addressing though.

2024-08-25 04:05 UTC, ZachZimm commented
I pushed a new commit based on your feedback. I did run pre-commit this time (sorry, I'd never heard of it before) and there shouldn't be any extra comments or prints.

2024-09-10 12:30 UTC, Blaizzy commented on fastmlx/utils.py
>      prompt_tokens = mx.array(tokenizer.encode(prompt))
The problem is that `processor` in some models it's the `tokenizer` and in others it has a the `tokenizer` as a attribute:
```python
    if image_processor is not None:
        prompt_tokens = mx.array(processor.encode(prompt))
        tokenizer = processor
    else:
        prompt_tokens = mx.array(processor.tokenizer.encode(prompt))
        tokenizer = processor.tokenizer
```
Link: https://github.com/Blaizzy/mlx-vlm/blob/d17b966cf76a16be93d06aa6eb5a4ae5a3954e46/mlx_vlm/utils.py#L900C1-L905C40

2024-09-10 12:30 UTC, Blaizzy commented on fastmlx/utils.py
> +    print(f"Prompt tokens: {prompt_token_len}")
ping 👆🏾

2024-09-10 12:34 UTC, Blaizzy commented
@ZachZimm please update the tests to support token info, this is what causing them to fail.

2024-09-12 21:32 UTC, ZachZimm commented on fastmlx/utils.py
>      prompt_tokens = mx.array(tokenizer.encode(prompt))
I'm not sure I follow your meaning. It seems to me that the distinction between LM and VLM models is already handled to account for the difference. The scope you identified with this comment is under a strictly LM function I believe, and so `tokenizer` is the only option.

Under `vlm_stream_generator()` we do `prompt_tokens = len(mx.array(processor.encode(prompt)))`. 
And under `lm_stream_generator()` we do `prompt_tokens = mx.array(tokenizer.encode(prompt))`.

2024-10-29 22:31 UTC, merged